//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje_RentACar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Araclar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Araclar()
        {
            this.KiradakiAraclar = new HashSet<KiradakiAraclar>();
            this.MusaitAraclar = new HashSet<MusaitAraclar>();
            this.Raporlar = new HashSet<Raporlar>();
        }
    
        public int ID { get; set; }
        public string Plaka { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public Nullable<int> Yıl { get; set; }
        public string Yakit { get; set; }
        public string Vites { get; set; }
        public Nullable<int> SonKilometre { get; set; }
        public string MotorCesidi { get; set; }
        public byte[] Resim { get; set; }
        public string Cekis { get; set; }
        public Nullable<int> Kapi { get; set; }
        public string KasaTipi { get; set; }
        public string Renk { get; set; }
        public Nullable<int> Hasar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KiradakiAraclar> KiradakiAraclar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MusaitAraclar> MusaitAraclar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Raporlar> Raporlar { get; set; }
    }
}
