//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje_RentACar
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusaitAraclar
    {
        public int ID { get; set; }
        public Nullable<int> AracID { get; set; }
        public string AracPlaka { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public Nullable<int> Yil { get; set; }
    
        public virtual Araclar Araclar { get; set; }
    }
}
